//
//  InstructionsPresenter.swift
//  FWFaceAuth
//
//  Created by Grecia Escárcega on 14/01/20.
//  Copyright (c) 2020 Grecia Escárcega. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstructionsPresenterDelegate {
}

class InstructionsPresenter: InstructionsPresenterDelegate {
    weak var viewController: InstructionsViewControllerDelegate?
}
